### ISSUE TITLE
Wrong repository description & tags

### ISSUE THREAD

**Issue by Lemonzyy** [fishfolks/jumpy#478]
### Problem
Since the rewrite with Bevy, the about section and the tags of this repository is no longer correct.
![image](https://user-images.githubusercontent.com/47032639/200178320-cb608482-5227-4ce3-811a-f6e796b19b51.png)
### Solution
* Update the about section:
```diff
- Tactical 2D shooter in fishy pixels style. Made with Rust-lang and Macroquad 🦀🌶
+ Tactical 2D shooter in fishy pixels style. Made with Rust-lang and Bevy 🦀🌶
```
* Replace the Macroquad tag with the Bevy tag.

**Comment by zicklag** [comment]
Thanks for the call out. Fixed!
